### ISSUE TITLE
reset SSH host keys

### ISSUE THREAD

**Issue by jishi** [geeeyetee/SonosAmpJuicePi#1]
Hey, here is some useful feedback:

My image is cleaned of ssh-host keys and contains a first-boot script to "persist" the generated host keys after first boot to avoid duplicating the SSH host keys for every installation (they should be unique for each machine, preferably).

If you don't want to muck around creating an image without host keys, you should atleast give instructions on how to reset them, basically:

 I don't recall exact folder where these reside, but I think this is it:
`rm /etc/sshd/ssh_host_*`
`lbu_commit`

It will generate new keys upon reboot now.

After rebooting, login and run `lbu_commit` again

If you want to add a first-boot script, put this into /etc/local.d/first-boot.start
```
#!/bin/sh
rm /etc/local.d/first-boot.start
/sbin/lbu_commit
```

and make first-boot.start executable. Remove the ssh_host_* keys, then run `lbu_commit` and shut down the machine. Now you would have an image that would regenerate keys when first booted, and then persist the new keys for subsequent reboots.

**Comment by Adam-S-Daniel** [comment]
Does this apply even though I am not using  node-sonos-http-api?

**Comment by jishi** [comment]
Yes, this is related to the security of the underlying Linux operating
system, and is an issue for all Linux images with sshd installed.

**Comment by Adam-S-Daniel** [comment]
Thanks! I added your instructions to readme.md.
