### ISSUE TITLE
Feature Request: Use MQTT to power amps on/off with tasmota switches.

### ISSUE THREAD

**Issue by rssalerno** [geeeyetee/SonosAmpJuicePi#5]
Please consider adding the ability to switch amplifiers on/off using MQTT or REST to control ESP8266-based switches running [tasmota](https://tasmota.github.io/docs/).  Examples of such switches include [Sonoff Basic](https://www.amazon.com/dp/B07KP8THFG) and [Gosund Power Plugs](https://www.amazon.com/Assistant-Required-Enabled-Control-Gosund/dp/B072ZX8RTZ/). These plugs are inexpensive and quick & easy to implement.

This approach has some advantages.  For example, the Pi running SonosAmpJuicePi can be situated remotely from the amplifier, which is useful where multiple amplifiers are located in different parts of the building.  In fact it could run as a service on any suitable machine as switching is done via MQTT and/or REST, rather than GPIO pins.  Deploying a new amplifier would be as easy as plugging the switch into the mains outlet, plugging the amp into the switch, and editing the configuration to accomodate the new amp.

**Comment by Adam-S-Daniel** [comment]
Sorry, but I'm not really maintaining this project anymore as I sold my whole setup to the buyer of the house I owned when I created this. I might suggest forking this project to a `SonosAmpJuice` or perhaps `SonosAmpJuiceRest` since, as you say, it would not be Pi-specific.
